import { ImageBackground } from "react-native";
const Images = {
  logo: require("./logo/logo.png"),
  rounded: require("./img_rounded.png"),
  shape: require("./img_shape.png"),
  background: require("./img_background.png"),
  onboarding: {
    onboarding01: require("./onboarding/img_intro_1.png"),
    onboarding02: require("./onboarding/img_intro_2.png"),
    onboarding03: require("./onboarding/img_intro_3.png"),
    onboarding04: require("./onboarding/img_intro_4.png"),
    onboarding05: require("./onboarding/img_intro_5.png"),
    onboarding06: require("./onboarding/img_intro_6.png"),
    onboarding07: require("./onboarding/img_intro_7.png"),
    onboarding08: require("./onboarding/img_intro_8.png"),
    onboarding09: require("./onboarding/img_intro_9.png"),
    onboarding10: require("./onboarding/img_intro_10.png"),
    onboarding11: require("./onboarding/img_intro_11.png"),
    onboarding12: require("./onboarding/img_intro_12.png"),
    onboarding13: require("./onboarding/img_intro_13.png"),
  },
  auth: {
    folder: require("./auth/img_folder.png"),
    piggybank: require("./auth/img_piggybank.png"),
    target: require("./auth/img_target.png"),
    shield: require("./auth/img_shield.png"),
    background_01: require("./auth/img_background_01.png"),
    background_02: require("./auth/img_background_02.png"),
    hand: require("./auth/img_hand.png"),
    auth: require("./auth/img_auth.png"),
    frame: require("./auth/img_frame.png"),
    verify: require("./auth/img_verify.png"),
  },
  avatar: {
    avatar: require("./avatar/img_avatar.png"),
    avatar01: require("./avatar/img_avatar_01.png"),
    avatar02: require("./avatar/img_avatar_02.png"),
    avatar03: require("./avatar/img_avatar_03.png"),
    avatar04: require("./avatar/img_avatar_04.png"),
    avatar05: require("./avatar/img_avatar_05.png"),
    avatar06: require("./avatar/img_avatar_06.png"),
    avatar07: require("./avatar/img_avatar_07.png"),
    avatar08: require("./avatar/img_avatar_08.png"),
    avatar09: require("./avatar/img_avatar_09.png"),
    avatar10: require("./avatar/img_avatar_10.png"),
  },
  profile_girl: require("./profile/img_girl.png"),
  exam: {
    achievement: require('./exam/achievement.png'),
    texting: require('./exam/texting.png'),
    penalty: require('./exam/penalty.png'),
  },
};
export default Images;
